name: CI

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build: 
    runs-on:
      ubuntu-latest

    steps:
    - name: Test GitHUb action command
      run: echo github action ok!
